[project]
requires-python = ">=3.6"

[dependencies]
numpy = "^1.19"

[build-system]
requires = ["setuptools>=42", "wheel", "cmake==3.21.1", "numpy==1.19.4"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp36-* cp37-* cp38-* cp39-*"
skip = "*-win32 *-manylinux_i686"

manylinux-x86_64-image = "manylinux2014"
archs = "auto64"

[tool.cibuildwheel.linux]
before-build = [
    "yum install -y wget freetype-devel zlib-devel libpng12-devel pixman-devel eigen3-devel",

    # compile cairo (RDKit needs older/other version than in centOS7 repo)
    "wget https://www.cairographics.org/releases/cairo-1.10.0.tar.gz --no-check-certificate",
    "tar xvf cairo-*",
    "cd cairo-*",
    "./configure",
    "make -j 20",
    "make install",
    "cd ..",
]

[tool.cibuildwheel.macos]

before-build = [
    "brew install cairo eigen gnu-sed",
    "pip install delocate==0.8.2",
    ]

repair-wheel-command = [
    "export DYLD_LIBRARY_PATH='/usr/local/lib:/usr/lib'",
    "delocate-listdeps {wheel}",
    "delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}",
]

[tool.cibuildwheel.windows]

          